import{FilesetResolver,HandLandmarker}from"https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/vision_bundle.mjs";
const WASM="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm",MODEL="https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";
const $=s=>document.querySelector(s);let lm,stream,raf,gameKind,round=0,total=0,t=60,timerId,grab=null,pinch=false,mouseDown=false;
const names={altar:"ภารกิจ ๑ · จัดโต๊ะหมู่บูชา",sort:"ภารกิจ ๒ · นักคัดแยกขยะ",quiz:"ภารกิจ ๓ · ธรรมะท้าประลอง",fill:"ภารกิจ ๔ · เติมคำธรรมะ",moral:"ภารกิจ ๕ · พุทธศาสนิกชนตัวน้อย",tree:"ภารกิจ ๖ · ต้นไม้แห่งความดี"};
function score(n){round+=n;total+=n;$("#score").textContent=round;$("#menuScore").textContent=`คะแนนสะสม ${total}`}
function toast(s){$("#feedback").textContent=s;$("#feedback").classList.add("show");clearTimeout(toast.x);toast.x=setTimeout(()=>$("#feedback").classList.remove("show"),900)}
function timer(n=60){t=n;$("#timer").textContent=t;clearInterval(timerId);timerId=setInterval(()=>{t--;$("#timer").textContent=t;if(t<=0){clearInterval(timerId);toast("หมดเวลา ✨");setTimeout(home,1000)}},1000)}
async function camera(){try{if(!lm){const v=await FilesetResolver.forVisionTasks(WASM);lm=await HandLandmarker.createFromOptions(v,{baseOptions:{modelAssetPath:MODEL,delegate:"GPU"},runningMode:"VIDEO",numHands:1,minHandDetectionConfidence:.55,minHandPresenceConfidence:.55,minTrackingConfidence:.55})}stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}},audio:false});$("#camera").srcObject=stream;await $("#camera").play();$("#status").textContent="กล้องพร้อมแล้ว";loop()}catch(e){$("#status").textContent="เปิดกล้องไม่ได้ — ใช้เมาส์/สัมผัสทดสอบได้"}}
function loop(){cancelAnimationFrame(raf);const f=()=>{const v=$("#camera");if(lm&&v.readyState>=2){const r=lm.detectForVideo(v,performance.now());if(r.landmarks?.[0]){const a=r.landmarks[0],x=(1-a[8].x)*innerWidth,y=a[8].y*innerHeight,d=Math.hypot(a[8].x-a[4].x,a[8].y-a[4].y);$("#pointer").style.display="block";$("#pointer").style.left=x-14+"px";$("#pointer").style.top=y-14+"px";const p=d<.062||pinch&&d<.085;if(p&&!pinch){grab=hit(x,y)}if(p&&grab)move(grab,x,y);if(!p&&pinch&&grab){release(grab,x,y);grab=null}pinch=p}else $("#pointer").style.display="none"}raf=requestAnimationFrame(f)};f()}
function hit(x,y){return[...$("#area").querySelectorAll("[data-drag]")].find(e=>{const r=e.getBoundingClientRect();return x>r.left&&x<r.right&&y>r.top&&y<r.bottom})}
function move(e,x,y){e.style.position="fixed";e.style.left=x-e.offsetWidth/2+"px";e.style.top=y-e.offsetHeight/2+"px";e.style.zIndex=90}
function release(e,x,y){if(gameKind==="sort")sortRelease(e,x,y);if(gameKind==="fill")fillRelease(e);if(gameKind==="tree")treeRelease(e,x,y);if(gameKind==="altar")altarRelease(e,x,y)}
function altar(){$("#title").innerHTML="<h2>จัดโต๊ะหมู่บูชา</h2><p>จัดองค์ประกอบให้เหมาะสม</p>";$("#hint").textContent="🤏 ลากสิ่งของไปยังตำแหน่งที่เหมาะสม";$("#area").innerHTML='<div class="altar"><div class="tier a"></div><div class="tier b"></div><div class="tier c"></div></div><div class="tray"><div class="drag" data-drag>🪷</div><div class="drag" data-drag>🪔</div><div class="drag" data-drag>🌸</div><div class="drag" data-drag>🕯️</div></div>';timer()}
function altarRelease(e,x,y){const r=$("#area").getBoundingClientRect();if(y>r.top+r.height*.25&&y<r.top+r.height*.72){e.remove();score(10);toast("วางได้ดี +10");if(!$("#area .drag"))finish("จัดโต๊ะสำเร็จ 🪷")}else{e.style.position="";e.style.left="";e.style.top=""}}
function sort(){let ws=["🍌","🥤","📦","🔋","🍎","🧴","📰","💡"];$("#title").innerHTML="<h2>นักคัดแยกขยะ</h2><p>แยกให้ถูกถัง รักษ์โรงเรียน รักษ์โลก</p>";$("#hint").textContent="🤏 หยิบขยะแล้วลากลงถัง";$("#area").innerHTML='<div class="bins"><div class="bin green">🟢<br>ทั่วไป</div><div class="bin blue">🔵<br>รีไซเคิล</div><div class="bin yellow">🟡<br>กระดาษ</div><div class="bin red">🔴<br>อันตราย</div></div>';ws.forEach((w,i)=>{let d=document.createElement("div");d.className="waste";d.textContent=w;d.dataset.drag=1;d.dataset.type=i%4===0?"green":i%4===1?"blue":i%4===2?"yellow":"red";d.style.left=8+(i%4)*23+"%";d.style.top=8+Math.floor(i/4)*28+"%";$("#area").appendChild(d)});timer()}
function sortRelease(e,x,y){let b=[...$("#area .bin")].find(q=>{let r=q.getBoundingClientRect();return x>r.left&&x<r.right&&y>r.top&&y<r.bottom}),c=b&&[...b.classList].find(k=>/green|blue|yellow|red/.test(k));if(c===e.dataset.type){e.remove();score(10);toast("แยกถูกต้อง +10");if(!$("#area .waste"))finish("แยกขยะครบแล้ว 🎉")}else{e.style.position="";e.style.left="";e.style.top="";toast("ลองใหม่อีกครั้ง")}}
const qs=[["การพูดความจริงแสดงถึงคุณธรรมข้อใด?","ซื่อสัตย์","ประมาท"],["เห็นเพื่อนลำบาก เราควรทำอย่างไร?","ช่วยเหลือ","เพิกเฉย"],["การมีวินัยควรเริ่มจากอะไร?","ทำตามกติกา","ทำตามใจ"],["การทำความดีควรทำเมื่อใด?","ทุกวัน","เฉพาะเมื่อมีคนเห็น"],["ชาวพุทธที่ดีควรละเว้นสิ่งใด?","ความชั่ว","ความดี"]];
function quiz(){let q=0;$("#title").innerHTML="<h2>ธรรมะท้าประลอง</h2><p>คิดดี ตอบดี ทำดี</p>";$("#hint").textContent="☝️ เลือกคำตอบที่ถูกต้อง";timer();const draw=()=>{$("#area").innerHTML=`<div class="card"><div class="question">${qs[q][0]}</div><div class="answers"><button class="answer" data-ok="1">A · ${qs[q][1]}</button><button class="answer" data-ok="0">B · ${qs[q][2]}</button></div><p>ข้อ ${q+1}/${qs.length}</p></div>`};draw();$("#area").onclick=e=>{let a=e.target.closest(".answer");if(!a)return;if(a.dataset.ok==="1"){score(10);q++;toast("ถูกต้อง +10");q===qs.length?finish("ผ่านครบทุกข้อ 🎉"):draw()}else toast("ลองคิดอีกครั้ง")}}
const fs=[["ชาวพุทธที่ดีควร ______ ทำความดี ละเว้นความชั่ว","ตั้งใจ"],["เมื่อเห็นเพื่อนลำบาก เราควร ______ เพื่อน","ช่วยเหลือ"],["การพูดความจริงเป็นการแสดงถึงความ ______","ซื่อสัตย์"],["นักเรียนที่มีความ ______ จะตั้งใจเรียน","ขยัน"],["เราควรมี ______ ต่อผู้อื่น","เมตตา"]];
function fill(){let q=0;$("#title").innerHTML="<h2>เติมคำธรรมะ</h2><p>เติมคำให้เหมาะสม</p>";$("#hint").textContent="🤏 ลาก/แตะคำตอบ";timer();const draw=()=>{$("#area").innerHTML=`<div class="card"><div class="question">${fs[q][0].replace("______","<span style='color:#ffd36e'>______</span>")}</div><div class="words">${[fs[q][1],"ละเลย","โกหก","หลีกหนี"].sort(()=>Math.random()-.5).map(w=>`<button class="word" data-w="${w}" data-drag>${w}</button>`).join("")}</div><p>ข้อ ${q+1}/${fs.length}</p></div>`};draw();$("#area").onclick=e=>{let w=e.target.closest(".word");if(!w)return;if(w.dataset.w===fs[q][1]){score(10);q++;toast("ถูกต้อง +10");q===fs.length?finish("เติมคำครบแล้ว 🎉"):draw()}else toast("คำนี้ยังไม่เหมาะ")}}
function fillRelease(e){e.click()}
const ms=[["ห้องเรียนมีขยะเต็มพื้น","ช่วยกันเก็บและทิ้งให้ถูกถัง","เดินผ่านแล้วไม่สนใจ"],["เพื่อนลืมอุปกรณ์การเรียน","แบ่งปันหรือช่วยหาให้เพื่อน","หัวเราะเยาะเพื่อน"],["พบของที่ไม่ใช่ของตนเอง","นำส่งครูหรือถามหาเจ้าของ","เก็บไว้เป็นของตน"]];
function moral(){let q=0;$("#title").innerHTML="<h2>พุทธศาสนิกชนตัวน้อย</h2><p>เลือกการกระทำที่สะท้อนความดี</p>";$("#hint").textContent="เลือกสิ่งที่เป็นประโยชน์ต่อผู้อื่น";timer();const draw=()=>{$("#area").innerHTML=`<div class="card"><div class="question">${ms[q][0]}</div><div class="choices"><button class="choice" data-ok="1">${ms[q][1]}</button><button class="choice" data-ok="0">${ms[q][2]}</button></div></div>`};draw();$("#area").onclick=e=>{let c=e.target.closest(".choice");if(!c)return;c.dataset.ok==="1"?(score(10),q++,toast("เลือกทำความดี +10"),q===ms.length?finish("คุณคือพุทธศาสนิกชนตัวน้อย 🌱"):draw()):toast("ลองเลือกสิ่งที่ดีต่อผู้อื่น")}}
function tree(){let vs=["ซื่อสัตย์","กตัญญู","มีน้ำใจ","ขยัน","หมั่นเพียร","มีวินัย","เมตตา","อดทน"];$("#title").innerHTML="<h2>ต้นไม้แห่งความดี</h2><p>เติมใบไม้คุณธรรมให้ต้นไม้เติบโต</p>";$("#hint").textContent="🤏 ลากใบไม้ไปวางบนต้นไม้";$("#area").innerHTML='<div class="tree">🌳</div><div class="leaves"></div><div class="virtues">'+vs.map(v=>`<div class="virtue" data-v="${v}" data-drag>🍃 ${v}</div>`).join("")+"</div>";timer()}
function treeRelease(e,x,y){let r=$("#area .tree").getBoundingClientRect();if(x>r.left-80&&x<r.right+80&&y>r.top-50&&y<r.bottom+50){let l=document.createElement("div");l.className="leaf";l.textContent="🍃";l.title=e.dataset.v;l.style.left=x-$("#area").getBoundingClientRect().left+"px";l.style.top=y-$("#area").getBoundingClientRect().top+"px";$("#area .leaves").appendChild(l);e.remove();score(10);toast(e.dataset.v+" +10");if(!$(".virtue"))finish("ต้นไม้แห่งความดีเบ่งบาน 🌳✨")}else{e.style.position="";e.style.left="";e.style.top=""}}
function finish(s){clearInterval(timerId);toast(s);setTimeout(home,1300)}
function start(kind){gameKind=kind;round=0;$("#gameName").textContent=names[kind];$("#menu").classList.add("hidden");$("#permission").classList.remove("hidden");$("#status").textContent="พร้อมเปิดกล้องสำหรับ "+names[kind]}
$("#start").onclick=async()=>{$("#permission").classList.add("hidden");$("#game").classList.remove("hidden");await camera();({altar,sort,quiz,fill,moral,tree}[gameKind])()};
function home(){clearInterval(timerId);cancelAnimationFrame(raf);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$("#camera").srcObject=null;$("#game").classList.add("hidden");$("#permission").classList.add("hidden");$("#menu").classList.remove("hidden")}
$("#home").onclick=home;document.querySelectorAll(".grid button").forEach(b=>b.onclick=()=>start(b.dataset.game));
